/* Banco de dados: */

CREATE TABLE USUARIOS (
    CPF BIGINT UNIQUE PRIMARY KEY,
    NOME VARCHAR,
    LOGIN VARCHAR,
    ENDEREÇO VARCHAR,
    CIDADE VARCHAR,
    EMAIL VARCHAR,
    SENHA VARCHAR,
    DATANASCIMENTO DATE,
    RG BIGINT,
    SITUACAO BOOLEAN,
    NUMEROCONTRATO INT,
    TIPO VARCHAR
);
 

CREATE TABLE NUMERO (
    NUMERO BIGINT PRIMARY KEY,
    SIM BIGINT,
    CPF BIGINT,
    NUMEROCONTRATO INT,
    UNIQUE (NUMERO, SIM)
);

CREATE TABLE CONTRATOS (
    NUMEROCONTRATO INT PRIMARY KEY UNIQUE,
    CPF BIGINT,
    NUMERO BIGINT
);

CREATE TABLE APARELHOS (
    ID INT PRIMARY KEY UNIQUE,
    MARCA VARCHAR,
    MODELO VARCHAR,
    NUEMEROSERIE VARCHAR,
    NUMERO BIGINT,
    ESTOQUE INT,
    DTENTREGA DATE
);

CREATE TABLE FATURAS (
    ID INT PRIMARY KEY,
    NUMERO BIGINT,
    DATAINSERCAO DATE,
    MESFATURA INT,
    VALOR DECIMAL
);
 
ALTER TABLE NUMERO ADD CONSTRAINT FK_NUMERO_3
    FOREIGN KEY (CPF)
    REFERENCES USUARIO (CPF);

 ALTER TABLE NUMERO ADD CONSTRAINT FK_NUMERO_4
    FOREIGN KEY (NUMEROCONTRATO)
    REFERENCES CONTRATOS (NUMEROCONTRATO);

 ALTER TABLE CONTRATOS ADD CONSTRAINT FK_CONTRATOS_3
	FOREIGN KEY (CPF)
    REFERENCES USUARIO (CPF);
 
ALTER TABLE CONTRATOS ADD CONSTRAINT FK_CONTRATOS_4
    FOREIGN KEY (NUMERO)
    REFERENCES NUMERO (NUMERO);


ALTER TABLE APARELHOS ADD CONSTRAINT FK_APARELHOS_3
    FOREIGN KEY (NUMERO)
    REFERENCES NUMERO (NUMERO);

 
ALTER TABLE FATURAS ADD CONSTRAINT FK_FATURAS_2
    FOREIGN KEY (NUMERO)
    REFERENCES NUMERO (NUMERO);



